name: 'Shai-Hulud 2.0 Detector'
description: 'Detect compromised npm packages from the Shai-Hulud 2.0 supply chain attack'
author: 'gensecaihq'
branding:
  icon: 'shield'
  color: 'red'

inputs:
  fail-on-critical:
    description: 'Fail the action if critical severity packages are found'
    required: false
    default: 'true'
  fail-on-high:
    description: 'Fail the action if high or critical severity packages are found'
    required: false
    default: 'false'
  fail-on-any:
    description: 'Fail the action if any compromised packages are found'
    required: false
    default: 'false'
  scan-lockfiles:
    description: 'Scan lockfiles (package-lock.json, yarn.lock) for transitive dependencies'
    required: false
    default: 'true'
  scan-node-modules:
    description: 'Scan node_modules directory for installed packages'
    required: false
    default: 'false'
  output-format:
    description: 'Output format: text, json, or sarif'
    required: false
    default: 'text'
  working-directory:
    description: 'Directory to scan (defaults to repository root)'
    required: false
    default: '.'

outputs:
  affected-count:
    description: 'Number of affected packages found'
  status:
    description: 'Scan status: clean or affected'
  scan-time:
    description: 'Time taken to complete the scan in milliseconds'
  results:
    description: 'JSON array of affected packages'
  sarif-file:
    description: 'Path to SARIF report file (when output-format is sarif)'

runs:
  using: 'node20'
  main: 'dist/index.js'
